version: '3.8'

services:
  # Nginx reverse proxy for domain handling
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
    networks:
      - pds-network
    depends_on:
      - solid-pds
      - test-vc-creator
      - mern-app
      - vc-verifier
      - did-registry

  # API Registry Service
  api-registry:
    build:
      context: ./api-registry
    container_name: api-registry
    ports:
      - "3005:3005"
    volumes:
      - ./api-registry:/app
      - ./data/api-registry:/data
    environment:
      - PORT=3005
      - SERVICE_NAME=api-registry
      - SERVICE_VERSION=1.0.0
      - API_KEY=your-api-key-here
    networks:
      - pds-network

  # DID Registry Service
  did-registry:
    build:
      context: ./did-registry
    container_name: did-registry
    ports:
      - "3001:3001"
    volumes:
      - ./did-registry:/app
      - ./data/did-registry:/data
    environment:
      - PORT=3001
      - SERVICE_NAME=did-registry
      - SERVICE_VERSION=1.0.0
      - API_REGISTRY_URL=http://api-registry:3005
      - API_REGISTRY_KEY=your-api-key-here
    networks:
      - pds-network
    depends_on:
      - api-registry

  # Solid PDS (Personal Data Store)
  solid-pds:
    image: solidproject/community-solid-server:latest
    container_name: solid-pds
    ports:
      - "3000:3000"
    volumes:
      - ./solid-pds:/app
      - ./data/solid-pds:/data
      - ./solid-pds/config:/config
    environment:
      - CSS_CONFIG=/config/default.json
      - CSS_PORT=3000
      - SERVICE_NAME=solid-pds
      - SERVICE_VERSION=1.0.0
      - API_REGISTRY_URL=http://api-registry:3005
      - API_REGISTRY_KEY=your-api-key-here
    networks:
      - pds-network
    depends_on:
      - api-registry

  # Test VC Creator Service (DRO)
  test-vc-creator:
    build:
      context: ./test-vc-creator
    container_name: test-vc-creator
    ports:
      - "3002:3002"
    volumes:
      - ./test-vc-creator:/app
      - ./data/test-vc-creator:/data
    environment:
      - PORT=3002
      - SERVICE_NAME=test-vc-creator
      - SERVICE_VERSION=1.0.0
      - SOLID_PDS_URL=http://solid-pds:3000
      - DID_REGISTRY_URL=http://did-registry:3001
      - API_REGISTRY_URL=http://api-registry:3005
      - API_REGISTRY_KEY=your-api-key-here
      - DRO_DOMAIN=dro.gov.uk.local
    networks:
      - pds-network
    depends_on:
      - solid-pds
      - api-registry
      - did-registry

  # VC Verifier Service
  vc-verifier:
    build:
      context: ./vc-verifier
    container_name: vc-verifier
    ports:
      - "3004:3004"
    volumes:
      - ./vc-verifier:/app
      - ./data/vc-verifier:/data
    environment:
      - PORT=3004
      - SERVICE_NAME=vc-verifier
      - SERVICE_VERSION=1.0.0
      - DID_REGISTRY_URL=http://did-registry:3001
      - API_REGISTRY_URL=http://api-registry:3005
      - API_REGISTRY_KEY=your-api-key-here
    networks:
      - pds-network
    depends_on:
      - api-registry
      - did-registry

  # MERN App Extension
  mern-app:
    build:
      context: ./mern-app
    container_name: mern-app
    ports:
      - "3003:3003"
    volumes:
      - ./mern-app:/app
      - ./data/mern-app:/data
    environment:
      - PORT=3003
      - SERVICE_NAME=mern-app
      - SERVICE_VERSION=1.0.0
      - SOLID_PDS_URL=http://solid-pds:3000
      - VC_VERIFIER_URL=http://vc-verifier:3004
      - API_REGISTRY_URL=http://api-registry:3005
      - API_REGISTRY_KEY=your-api-key-here
      - APP_DOMAIN=benefits.gov.uk.local
    networks:
      - pds-network
    depends_on:
      - solid-pds
      - api-registry
      - vc-verifier

networks:
  pds-network:
    driver: bridge
