version: '3.8'

services:
  # Nginx reverse proxy for domain handling
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
    networks:
      - pds-network
    depends_on:
      - solid-pds
      - DRO
      - FEP
      - vc-verifier

  # API Registry Service
  api-registry:
    build:
      context: ./api-registry
    container_name: api-registry
    ports:
      - "3005:3005"
    volumes:
      - ./api-registry:/app
      - ./data/api-registry:/data
    environment:
      - PORT=3005
      - SERVICE_NAME=api-registry
      - SERVICE_VERSION=1.0.0
      - API_KEY=your-api-key-here
    networks:
      - pds-network

  # Solid PDS (Personal Data Store)
  solid-pds:
    image: solidproject/community-solid-server:latest
    container_name: solid-pds
    ports:
      - "3000:3000"
    volumes:
      - ./solid-pds:/app
      - ./data/solid-pds:/data
      - ./solid-pds/config:/config
    environment:
      - CSS_CONFIG=/config/default.json
      - CSS_PORT=3000
      - SERVICE_NAME=solid-pds
      - SERVICE_VERSION=1.0.0
      - API_REGISTRY_URL=http://api-registry:3005
      - API_REGISTRY_KEY=your-api-key-here
    networks:
      - pds-network
    depends_on:
      - api-registry

  # Test VC Creator Service (DRO)
  DRO:
    build:
      context: ./DRO
    container_name: DRO
    ports:
      - "3002:3002"
    volumes:
      - ./DRO:/app
      - ./data/DRO:/data
    environment:
      - PORT=3002
      - SERVICE_NAME=DRO
      - SERVICE_VERSION=1.0.0
      - SOLID_PDS_URL=http://solid-pds:3000
      - API_REGISTRY_URL=http://api-registry:3005
      - API_REGISTRY_KEY=your-api-key-here
      - DRO_DOMAIN=dro.gov.uk.local
    networks:
      - pds-network
    depends_on:
      - solid-pds
      - api-registry

  # VC Verifier Service
  vc-verifier:
    build:
      context: ./vc-verifier
    container_name: vc-verifier
    ports:
      - "3004:3004"
    volumes:
      - ./vc-verifier:/app
      - ./data/vc-verifier:/data
    environment:
      - PORT=3004
      - SERVICE_NAME=vc-verifier
      - SERVICE_VERSION=1.0.0
      - API_REGISTRY_URL=http://api-registry:3005
      - API_REGISTRY_KEY=your-api-key-here
    networks:
      - pds-network
    depends_on:
      - api-registry

  # MERN App Extension (FEP)
  FEP:
    build:
      context: ./FEP
    container_name: FEP
    ports:
      - "3003:3003"
    volumes:
      - ./FEP:/app
      - ./data/FEP:/data
    environment:
      - PORT=3003
      - SERVICE_NAME=FEP
      - SERVICE_VERSION=1.0.0
      - SOLID_PDS_URL=http://solid-pds:3000
      - VC_VERIFIER_URL=http://vc-verifier:3004
      - API_REGISTRY_URL=http://api-registry:3005
      - API_REGISTRY_KEY=your-api-key-here
      - APP_DOMAIN=fep.gov.uk.local
      - APP_NAME=FEP Application
    networks:
      - pds-network
    depends_on:
      - solid-pds
      - api-registry
      - vc-verifier

networks:
  pds-network:
    driver: bridge
